version: '2'
services:
  jenkins:
    build: .
    ports:
      - "8050:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

